import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={`w-full h-full m-0 p-0`} lang="en">
            <body className={`w-full h-full m-0 p-0 ${inter.className}`}>{children}</body>
        </html>
    );
}
